WebUi/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WebUi.Models;
using WebUi.Helpers;
using WebUi.Services;
using System.Configuration;
using System.Net;

namespace WebUi.Controllers
{
    public class SearchController : Controller
    {
        private static readonly log4net.ILog _log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private string _truncateUrl;
        private Pager _pager
        {
            get
            {
                if (Session["pager"] == null)
                    Session["pager"] = new Pager();

                return (Pager)Session["pager"];
            }
            set
            {
                Session["pager"] = value;
            }
        }

        private OrganizationsSearch _search
        {
            get
            {
                if (Session["search"] == null)
                    Session["search"] = new OrganizationsSearch();

                return (OrganizationsSearch)Session["search"];
            }
            set
            {
                Session["search"] = value;
            }
        }

        private OrganizationsService _organizationsService;
        //private OrganizationsSearch _search;
        //private Pager _pager;


        public SearchController()
        {
            _organizationsService = new OrganizationsService(ConfigurationManager.ConnectionStrings["TestAppConnectionString"].ConnectionString);
            _truncateUrl = Convert.ToString(ConfigurationManager.AppSettings["TruncateUrl"]);
        }

        // GET: Search
        public ActionResult Index()
        {
            var model = new OrganizationsViewModel
            {
                Pager = new Pager(),
                Organizations = new List<SearchOrganizationsResult>(),
                Search = new OrganizationsSearch()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(OrganizationsSearch search)
        {
            _search = search;
            var model = _organizationsService.Search(search, new Pager());
            return View(model);
        }

        // update search (paginate, sort, etc). Returns partial with updated results.
        [HttpPost]
        public ActionResult UpdateSearch(OrganizationsViewModel search)
        {
            var model = new OrganizationsViewModel();
            try
            {
                model = _organizationsService.Search(_search, new Pager());
                _pager = model.Pager;                
            }
            catch(Exception ex)
            {
                ViewBag.ErrorTitle = "Error accessing Database";
                ViewBag.ErrorMessage = $"Please check the database connection string in the app.config file and the startup script has been run before proceeding. Error: {ex.Message}";
            }
            return PartialView("_SearchResults", model);
        }

        [HttpPost]
        public ActionResult ChangePage(int page)
        {
            var model = new OrganizationsViewModel();
            try
            {
                _pager.CurrentPage = page;
                model = _organizationsService.Search(_search, _pager);
                _pager = model.Pager;

                return PartialView("_SearchResults", model);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorTitle = "Error accessing Database";
                ViewBag.ErrorMessage = $"Please check the database connection string in the app.config file and the startup script has been run before proceeding. Error: {ex.Message}";
            }
            return PartialView("_SearchResults", model);
        }

        [HttpPost]
        public ActionResult Truncate()
        {
            try
            {
                using (var client = new WebClient())
                {
                    client.Headers[HttpRequestHeader.ContentType] = "application/x-www-form-urlencoded";
                    var data = "=secret";
                    var result = client.UploadString(_truncateUrl, "POST", data);
                    if (result == "\"ok\"")
                    {
                        return new HttpStatusCodeResult(200);
                    }
                    else
                    {
                        _log.Error($"An error has ocurred while  attempting to truncate table, got: {result}");
                        return new HttpStatusCodeResult(500, $"An error has ocurred while  attempting to truncate table, got: {result}");
                    }
                }
            }
            catch (Exception ex)
            {
                _log.Error($"An error has ocurred while posting the info: {ex.Message}");
                return new HttpStatusCodeResult(500, $"An error has ocurred while posting the info: {ex.Message}");
            }

        }
    }
}

WebUi/Views/Search/Index.cshtml
@model WebUi.Models.OrganizationsViewModel

<div class="panel panel-primary">

    <div class="card">
        <h5 class="card-header">
            Search Organizations
        </h5>
        <div class="card-body">
            @using (Html.BeginForm("Index", "Search", FormMethod.Post))
            {
                <div class="form-group">
                    <div class="form-group row">
                        <label for="Search_Name" class="col-sm-3 col-form-label float-sm-left">Organization name</label>
                        <div class="col-sm-7">
                            @Html.TextBoxFor(e => e.Search.Name, new { @class = "form-control", placeholder = "Type an organization name" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="Search_RowsPerPage" class="col-sm-3 col-form-label float-sm-left">Rows per page</label>
                        <div class="col-sm-3">
                        @Html.DropDownListFor(x => x.Search.RowsPerPage,
                        new List<SelectListItem> {
                        new SelectListItem { Text = "2", Value = "2" },
                        new SelectListItem { Text = "5", Value = "5" },
                        new SelectListItem { Text = "10", Value = "10" },
                        new SelectListItem { Text = "20", Value = "20" },
                        new SelectListItem { Text = "30", Value = "30" },
                        new SelectListItem { Text = "50", Value = "50" },
                          },new { @class = "form-control" })
                        </div>
                    </div>
                    <div>
                        <div class="form-check form-check-inline">
                            @Html.CheckBoxFor(e => e.Search.ShowParent, new { @class = "form-check-input" })
                            <label class="form-check-label" for="Search_ShowParent">Show Parent</label>
                        </div>
                        <div class="form-check form-check-inline">
                            @Html.CheckBoxFor(e => e.Search.ShowSisters, new { @class = "form-check-input" })
                            <label class="form-check-label" for="Search_ShowSisters">Show Sisters</label>
                        </div>
                        <div class="form-check form-check-inline">
                            @Html.CheckBoxFor(e => e.Search.ShowDaughters, new { @class = "form-check-input" })
                            <label class="form-check-label" for="Search_ShowDaughters">Show Daughters</label>
                        </div>

                    </div>

                </div>
                <button type="submit" class="btn btn-primary" onclick="">Submit</button>
            }
        </div>
        <div class="card-footer font-italic" style="background: #ECC6B6">
            <h6 class="float-right">If you would like to truncate the organizations table and enter a new payload, click Truncate: 
            @Ajax.ActionLink(
                "Truncate",
                "Truncate",
                null,
                new AjaxOptions {
                    HttpMethod ="POST",
                    OnBegin = "onBegin()",
                    OnFailure = "onError",
                    OnSuccess = "onSucess"
                }, 
                new { @class = "btn btn-danger" })           
            </h6>
        </div>
    </div>
    <div class="results" id="results">
        @if (Model.Organizations != null && Model.Organizations.Any())
        {

            Html.RenderPartial("_SearchResults", Model);
        }
        else
        {
            <h5 class="card-body">There are no organizations to display.</h5>
        }        
    </div>
</div>

<div class="modal fade" id="redirectingModal" tabindex="-1" role="dialog" aria-labelledby="redirectingModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="redirectingModalLabel">Success!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                The organizations table has been truncated successfully. You will be redirected to the main page in 3 seconds
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        function onBegin() {
            return (confirm('Are you sure you want to erase all data in the Organizations table?'));
        }

        function onError(response, status, error) {
            alert('An error has ocurred while attemting to truncate the table: ' + response.statusText);            
        }

        function onSucess() {
            $(document).ready(function () {
                $('#redirectingModal').modal();
            });
            window.setTimeout(function () {
                window.location.href = "@Url.Action("Index", "Home")"
            }, 3000);
        }
    </script>
}